### PR TITLE
Fix state/config loading, test on all PRs and add use case

### LINKED ISSUE #108: swap_backgrounds not working
I'm using lazy.nvim. I found out that `swap_background` option is not working. I tried to swap them with `on_palette` option and figured out that it is called twice and therefore not working. I believe it is a cause why `swap_backgrounds` is broken.

```
    {
      'AlexvZyl/nordic.nvim',
      event = 'VeryLazy',
      config = function()
        local counter = 0
        require('nordic').setup({
          on_palette = function(palette)
            counter = counter + 1
            print(counter, palette.gray0, palette.black1)
            local gray0 = palette.gray0
            palette.gray0 = palette.black1
            palette.black1 = gray0
            return palette
          end,
          -- swap_backgrounds = true,
        })
        vim.cmd('colorscheme nordic')
      end,
    },

```

### LINKED ISSUE #112: No selection highlight when transparent mode is enabled
Hi, i am using this theme almost half a year and everything was fine, but a couple weeks ago, after updating plugins - this strange bug appeared. I cannot find any similar issues (but there is a chance, that i'm just blind :) ), so have to create one.

**Problem definition**
There is no text highlight below selection in visual mode (no matter which mode is it: regular/line/block). Such behaviour appears only if the `transparent_bg` is set to `true`, otherwise everything works as it should be.

**PoC**
image
 
**Environment details**
 - OS: EndeavourOS Linux / MacOS 14 Sonoma
 - Terminals: alacritty / wezTerm
 - nvim 0.9.5
 - plugin manager: Lazy (latest stable)
 - nordic.nvim (tested on both main and dev branches)

**Nordic setup** is pretty much same as default, just added few mods.
```lua
    {
        'AlexvZyl/nordic.nvim',
        branch = "dev",
        lazy = false,
        priority = 1000,
        config = function()
            require 'nordic' .setup {
                -- This callback can be used to override the colors used in the palette.
                on_palette = function(palette) return palette end,
                -- Enable bold keywords.
                bold_keywords = false,
                -- Enable italic comments.
                italic_comments = true,
                -- Enable general editor background transparency.
                transparent_bg = true,
                -- Enable brighter float border.
                bright_border = false,
                -- Reduce the overall amount of blue in the theme (diverges from base Nord).
                reduced_blue = true,
                -- Swap the dark background with the normal one.
                swap_backgrounds = true,
                -- Override the styling of any highlight group.
                override = {
                    LineNr = {
                        -- fg = "#b07c05",
                        fg = "#60728A",
                        bold = true,
                    },
                },
                -- Cursorline options.  Also includes visual/selection.
                cursorline = {
                    -- Bold font in cursorline.
                    bold = false,
                    -- Bold cursorline number.
                    bold_number = true,
                    -- Avialable styles: 'dark', 'light'.
                    theme = 'dark',
                    -- Blending the cursorline bg with the buffer bg.
                    blend = 0.7,
                },
                noice = {
                    -- Available styles: `classic`, `flat`.
                    style = 'classic',
                },
                telescope = {
                    -- Available styles: `classic`, `flat`.
                    style = 'classic',
                },
                leap = {
                    -- Dims the backdrop when using leap.
                    dim_backdrop = false,
                },
                ts_context = {
                    -- Enables dark background for treesitter-context window
                    dark_background = true,
                }
            }
            vim.cmd.colorscheme 'nordic'
        end
    },
```

*Related notes to which I would like to draw attention*
On previous installed version (unfortunately I can't remember which one), even with enabled transparent background, floating windows (such as Lazy or Mason) kept their non-transparent bg, which in my opinion, was much more convenient than now. Perhaps it would be worth (if it is possible) making a separate switch to leave opaque color for them or at least change it?
image

**P.S.** Also want to thank you for creating and maintaining this marvelous theme!

### PR DESCRIPTION
**Pull request by 5-pebbles**
This PR improves the handling of state and config loading.

### CODE REVIEW

**Comment by AlexvZyl** [comment]
You can change the message if you want, but we are merging this into #113.

**Comment by 5-pebbles** [comment]
sorry, I misread that message.

**Comment by 5-pebbles** [comment]
I resolved conflicts then ran tests locally with act and they are passing.

I figure I should let you merge though if this is what you are looking for.

**Comment by AlexvZyl** [comment]
No longer need to run the tests locally! :)

**Comment by 5-pebbles** [comment]
Thanks.

**Comment by AlexvZyl** [comment]
Did you see I started a review?

**Comment by 5-pebbles** [comment]
No, I did not. Quite frankly this is the first project I have tried actually using GitHub for so I don't know any of this stuff.

**Comment by 5-pebbles** [comment]
Yeah, I have no idea what I am supposed to be doing.

**Comment by AlexvZyl** [comment]
No worries!  Ons step at a time.

I left comments (in this PR UI) on the changes you made.  Try and find them and respond to them.

**Comment by 5-pebbles** [comment]
I though comments showed up in this chat, but I don't see any. 
I also though they showed up on the Files changed tab but I don't see anything there either.

**Comment by 5-pebbles** [comment]
Ok, I can not see the code review I tested it on a private repo and it should be here but its not.

**Comment by AlexvZyl** [comment]
Scroll through the "files changed" tab.

**Comment by AlexvZyl** [comment]
Odd.  I will check it out tomorrow.

**Comment by 5-pebbles** [comment]
There are no comments there.

**Comment by 5-pebbles** [comment]
Alright Good Night!

File: lua/nordic/colors/nordic.lua [hunk 1]
```diff
@@ -25,10 +25,10 @@ local palette = {
...
 
     -- Dim white.
-    -- `white0` is used as the default fg, and has a blue tint.
-    -- Reduce that amount of tint.
-    white0_alt = '#C0C8D8',
-    white0 = '#BBC3D4',
+    -- default fg, has a blue tint.
+    white0_normal = '#BBC3D4',
+    -- less blue tint
+    white0_reduce_blue = '#C0C8D8',
```
Comment (AlexvZyl) [inline lua/nordic/colors/nordic.lua:31]: Rather not change these names, they are perfectly fine.

File: lua/nordic/init.lua [hunk 2]
```diff
@@ -13,15 +13,13 @@ function M.load(opts)
...
-
-    -- Apply theme.
-    local G = require 'nordic.groups'
-    U.highlight(G.get_groups())
-    G.set_term_colors()
+    -- Setup colors
+    require('nordic.colors').extend_palette()
+
+    -- Apply theme
+    local groups = require 'nordic.groups'
```
Comment (AlexvZyl) [inline lua/nordic/init.lua:20]: The current convention (in this codebase at least) is to name modules with a capital letter.  So this should be `G`.  Not a big deal, just a stylistic choice.

File: lua/nordic/init.lua [hunk 3]
```diff
@@ -31,6 +29,6 @@ end, {
     nargs = 1,
 })
 
-M.setup = require 'nordic.config'.setup
+M.setup = require('nordic.config').setup
```
Comment (AlexvZyl) [inline lua/nordic/init.lua:32]: The formatter (ran when merged into main) takes care of these things.

File: lua/nordic/groups/native.lua [hunk 4]
```diff
@@ -66,7 +66,7 @@ function M.get_groups()
     G.htmlH1 = { fg = C.yellow.base, bold = true }
     G.htmlH2 = { fg = C.orange.base }
     G.Link = { fg = C.blue1, underline = true }
-    G.CodeBlock = { bg = C.black1, fg = C.fg }
+    G.CodeBlock = { bg = C.bg_float, fg = C.fg }
```
Comment (AlexvZyl) [inline lua/nordic/groups/native.lua:69]: Code blocks are not floating?

File: lua/nordic/groups/native.lua [hunk 5]
```diff
@@ -163,7 +163,7 @@ function M.get_groups()
     G.PmenuThumb = { bg = C.gray2, fg = C.gray2 } -- Popup menu: Thumb of the scrollbar.
     G.Question = { fg = C.info } -- |hit-enter| prompt and yes/no questions
     G.QuickFixLine = { bg = C.bg_visual, bold = true } -- Current |quickfix| item in the quickfix window. Combined with |hl-CursorLine| when the cursor is there.
-    G.Search = { bg = C.black1, fg = C.yellow.bright, bold = true, underline = true } -- Last search pattern highlighting (see 'hlsearch').  Also used for similar items that need to stand out.
+    G.Search = { bg = C.bg_float, fg = C.yellow.bright, bold = true, underline = true } -- Last search pattern highlighting (see 'hlsearch').  Also used for similar items that need to stand out.
```
Comment (AlexvZyl) [inline lua/nordic/groups/native.lua:166]: Why did you change this to the float bg?

**Comment by AlexvZyl** [comment]
@5-pebbles You should be able to see the review now.

**Comment by 5-pebbles** [comment]
Yup I can.

File: lua/nordic/colors/nordic.lua (hunk 1 above)
Comment (5-pebbles) [reply lua/nordic/colors/nordic.lua:31]: If you are going to be able to reload the config, both values need to be separate.

You were leaving `white0` the same and adding `white_alt` (or something like that), however once you set white0 to alt you lose the original value of white and can't go back without closing and reopening neovim.

File: lua/nordic/init.lua (hunk 2 above)
Comment (5-pebbles) [reply lua/nordic/init.lua:20]: Ok I though capital letters were for globals I will change this.

File: lua/nordic/colors/nordic.lua (hunk 1 above)
Comment (AlexvZyl) [reply lua/nordic/colors/nordic.lua:31]: Sure, but leave the names "white0" and "white0_alt".

File: lua/nordic/init.lua (hunk 2 above)
Comment (AlexvZyl) [reply lua/nordic/init.lua:20]: Actually a better idea.  But we can change that in a different PR

File: lua/nordic/groups/native.lua (hunk 4 above)
Comment (5-pebbles) [reply lua/nordic/groups/native.lua:69]: But their background needs to change with swap backgrounds. I can't just switch the value of black1 and gray0 otherwise its just a toggle. 

I needed a value to store the current background colors, that cold be swapped, bg & bg_float seemed like the right fit seeing as they are already doing this for most of the highlights..

Functionally the code is the exact same but if you would like I can make another value in `extend_palette` for them.

File: lua/nordic/groups/native.lua (hunk 5 above)
Comment (5-pebbles) [reply lua/nordic/groups/native.lua:166]: I needed a value to store the current background colors, that cold be swapped, bg & bg_float seemed like the right fit seeing as they are already doing this for most of the highlights.

The same is true of all the other spots where I switched the two.

File: lua/nordic/init.lua (hunk 3 above)
Comment (5-pebbles) [reply lua/nordic/init.lua:32]: Thats cool

File: lua/nordic/colors/nordic.lua (hunk 1 above)
Comment (5-pebbles) [reply lua/nordic/colors/nordic.lua:31]: I can leave white0_alt but I would have to change white0.

I guess I could save a bool for if they are swapped right now but that seems like more of a mess.

Comment (5-pebbles) [reply lua/nordic/colors/nordic.lua:31]: The actual value of `white0` is the same its just set in `extend_palette` instead.

I just changed the names to `white0_normal` & `white0_alt` but I think its more understandable like this.

I could ensure that `white0` exists even if you import from `colors.nordic` (no `extend_palette`) but that should never happen. Unless you use the values in the default config but then I think its better that you have to explicitly use one or the other.

File: lua/nordic/groups/native.lua (hunk 4 above)
Comment (5-pebbles) [reply lua/nordic/groups/native.lua:69]: Wait you right about these I need another color for them because, bg_float is not functionally the same... its transparent when the background is. I will fix these, thanks for pointing them out.

**Comment by 5-pebbles** [comment]
I am thinking about separating `bg_highlight` and `bg_visual`.

I think `bg_highlight` makes sense for `Search` and `CodeBlock`, plus it was only used into places:
- `G.CursorColumn` & `G.CursorLine`
> which I would move to using bg_visual

Its value would look something like this.
```lua
C.bg_highlight = (options.swap_backgrounds and C.gray0) or C.black1
```

What do you think?

File: lua/nordic/init.lua (hunk 2 above)
Comment (AlexvZyl) [reply lua/nordic/init.lua]: Lets just leave it for now, that is actually the reason I wrote it like this.  Catppuccin also does this.

File: lua/nordic/colors/nordic.lua (hunk 1 above)
Comment (AlexvZyl) [reply lua/nordic/colors/nordic.lua:31]: Oh I see now.  Then it is fine.

File: lua/nordic/init.lua (hunk 2 above)
Comment (AlexvZyl) [reply lua/nordic/init.lua]: Remember to change this to G.

**Comment by 5-pebbles** [comment]
I don't know why its not showing up in the pr but 4856cf8 contains the proposed changes.

**Comment by 5-pebbles** [comment]
I re-selected fix/state as base to force sync.

**Comment by AlexvZyl** [comment]
Sure, I think that will work!

**Comment by AlexvZyl** [comment]
I think we need a better name than `bg_highlight`.  `bg_highlight` does not make sense for the search bar...

Maybe something like `bg_bar`?  What do you think?

**Comment by 5-pebbles** [comment]
I don't know I think `bg_highlight` is good, its the a highlighted section of background, eg a search item or code block.

But naming this is really not my forte so I will leave that up to you, but I used it for code blocks as well and `bg_bar` does not sound right for those.

**Comment by AlexvZyl** [comment]
Hmm.  I don't think we should use `black0` for code blocks.  Rather `black1` or maybe `black2`.

**Comment by 5-pebbles** [comment]
Agreed and that is already the case:

`G.CodeBlock = { bg = C.bg_highlight, fg = C.fg }`

`C.bg_highlight = (options.swap_backgrounds and C.gray0) or C.black1`

**Comment by AlexvZyl** [comment]
Ah okay I see, but search should be ``black0`.

**Comment by AlexvZyl** [comment]
Actually, we need `bg_statusline` and Search should use that.

**Comment by 5-pebbles** [comment]
Alright I will make a commit for that, but it was `black1` before and I was just following along with that.

**Comment by 5-pebbles** [comment]
So `bg_statusline` is none when transparent background is true do you want no search highlight?

What about using `bg_visual` its the black0 though I would like to make it customizable with something like #100. It might make sense for search to be the same color as visual section.

I also thought it might make sense to have transparent code blocks and I could add those in the same commit.

**Comment by 5-pebbles** [comment]
What do you think about my last comment ^ @AlexvZyl

**Comment by AlexvZyl** [comment]
Sorry @5-pebbles!

`bg_statusline` should not be `NONE` when transparent is enabled.

**Comment by AlexvZyl** [comment]
Also, with customisability, I want to add two callbacks:

1. To override the base palette before extension.
2. To override the extended colors as well.

But we should do this in a seperate PR.

**Comment by AlexvZyl** [comment]
The reason I want search to be `black0` is because search happens in the bottom bar, so should be `black0`.

**Comment by 5-pebbles** [comment]
> Sorry @5-pebbles!
> 
> `bg_statusline` should not be `NONE` when transparent is enabled.

Aright I will fix that, because it is `NONE` on main.

> The reason I want search to be `black0` is because search happens in the bottom bar, so should be `black0`.

To make sure we are both on the same page the search highlight is:



I will set it to `black0` but its set to `black1` on main.
I think it would make sense for it to be `bg_visual` but I can do that in my own config.

Also would it make sense for code blocks to be transparent with `transparent_bg`?
I think it would...

I will get to these tomorrow because I have a bunch of other stuff to do today.

**Comment by AlexvZyl** [comment]
Okay, this entire time I though the search highlight was that highlight that colors the bottom bar, where you type in the search.  The bottom bar should be `black0`, the ones you are referring to should either be a lighter black or some grey, which ever you think looks best.

As for the code blocks being transparent, I am not sure...  I think they should be.

**Comment by 5-pebbles** [comment]
> Okay, this entire time I though the search highlight was that highlight that colors the bottom bar, where you type in the search. The bottom bar should be `black0`, the ones you are referring to should either be a lighter black or some grey, which ever you think looks best.

I think they should be `bg_visual` same as the visual selection (that way they will also change with the light and dark cursorline setting).

> As for the code blocks being transparent, I am not sure... I think they should be.

Alright great because I already did that...

**Comment by 5-pebbles** [comment]
If you are okay with those changes I think everything in this pr is done.

**Comment by AlexvZyl** [comment]
Cool!
